# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - m2mclothingg

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://m2mdeploy.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_66458de6dbab4990b159ef45991a4b14 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8385c74232ff458db78deefd94c86ef4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: m2mdeploy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_66458de6dbab4990b159ef45991a4b14 }}/m2mappweb:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'm2mclothingg'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_87374aa3f11b40b7a0d52f403d44761f }}
        images: 'm2mdeploy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_66458de6dbab4990b159ef45991a4b14 }}/m2mappweb:${{ github.sha }}'